### ISSUE TITLE
Add FORD keyword handling in Fuego for analytic and approx Jacobian

### ISSUE THREAD

**Issue by drummerdoc** [AMReX-Combustion/PelePhysics#23]
A recent fix will (just did) add the native handling of the FORD keyword in order to properly deal with non-integer explicitly set reaction orders (such as what is used in the CH4 2-step mech).  This mod is not yet pulled through the code that generates Jacobians though.

In fact, there is generalized ability in place that for specific mechanisms, auxiliary files can be used to implement specific functions.  Typically this is used to implement a QSS model for CKWYP, for example.  However, those functions are not necessary called by the RHS functions in the ODE integrators, AND the are not consistent with the Jacobian code.  There should be some kind of indicator that only some of the functionality is available in these cases (until the full functionality is eventually added).

**Comment by whitmanscu** [comment]
A recent fix (Issue #41) added some FORD keyword handling to the CPickler for Fuego, but it appears to remain incompletely implemented. The most immediate issue I see is that only the GPU version of comp_qfqr was modified to use the FORD orders while the CPU code still needs the same change.

I'm commenting on this issue because I'd like FORD rates to be fully implemented and it's not immediately clear to me what changes past what I mentioned above need to be made to the Jacobian generation (or other routines) in order to do this.

**Comment by whitmanscu** [comment]
It looks to me like the code needs to be fixed for aJacobian_precond, aJacobian, and vcomp_wdot, in addition to the comp_qfqr CPU method I mentioned above. Am I missing anything? I tried making modifications in these places but I'm still getting crashes when I try and run a 2-step propane mechanism with FORD rates (I posted the chemistry file to the other issue).

**Comment by malihass** [comment]
closed by #414
