### ISSUE TITLE
Naming convention in mechanism.h

### ISSUE THREAD

**Issue by ldowen** [AMReX-Combustion/PelePhysics#39]
Looking at the indices in the generated mechanism.h files, it looks like a few issues might arise. One issue could be when the species have names like "CH2(S)" so the define will have parentheses in it. Another issue arises when the names have a minus (or possibly a plus) like "A4-". In the Aromatic_KrNara directory, the mechanism.h file shows a define statement of A4_ID 117 followed by an A4_ID 118 on the next line. The 117 is supposed to be A4 while the 118 is supposed to be for the A4-. However, it is overwriting the next define.

**Comment by AnneFelden** [comment]
Hi Landon

Yes you are correct. As of today I have enabled Fuego to recognize a few such characters. Namely (, ), * and -. The parenthesis are simply discarded, the - too and the * is replaced with a D. Note however that only the * gave me an error on the mechanism you mention. If you notice any other characters raising an error, let me know. Thanks

**Comment by awehrfritz** [comment]
Hi everyone,
I also noticed this issue in the mechanism.h files. In the current code, all dash/minus characters are simply removed which will lead to issues for ionic species in some mechanisms, see e.g.:
https://github.com/AMReX-Combustion/PelePhysics/blob/88b88e4afd6efdca6c932171938437c68f53a779/Support/Fuego/Mechanism/Models/Aromatic_KrNara/mechanism.h#L127-L128 
There are actually more characters allowed in species names, e.g. '=', that would cause issues in a preprocessor define, but I am not quite sure how those ones should be treated as I don't have an example handy.

A fix for this issue is in #40.

**Comment by drummerdoc** [comment]
@EnnaDelfen Can you resolve these two issues and close them out?

**Comment by EnnaDelfen** [comment]
No problem. Unless I hear otherwise I'll replace -/+ by n/p for neg and pos.
Also bear in mind that as of today, it is not a real "problem" if several (or even all) species share symbols. These defs in the mechanism.h are here to help a somewhat experienced user find the indice of a species of use to him !

**Comment by drummerdoc** [comment]
It's harmless, but it makes annoying build warnings :(
